# Generated by Django 5.1.4 on 2025-01-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(default='exit', help_text="Укажите ингредиенты с количеством (каждый с новой строки). Пример: 'Молоко - 200 мл'"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
