# Generated by Django 5.1.4 on 2025-01-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_ingredients_recipe_ingredients_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='', help_text='Опишите шаги приготовления, разделенные новой строкой.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_steps', to='recipes.recipe'),
        ),
    ]
